### ISSUE TITLE
Week 4 Review Ticket

### ISSUE THREAD

**Issue by kar722** [kar722/CSPTri3#6]
Total Score: 5.4/5

CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)
- [ ] CB Create Task Coding requirements documented
- [ ] Runtime of Code(with comments) on Replit/Intellij
Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio)
- [ ] Hack #1 Add Phone Number to Sign Up / Authorization screen
- [ ] Hack #2 Add logout to CRUD screen
- [ ] Hack #3 Add login_required to another portion of the project
- [ ] A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.

**Comment by PranavP04** [comment]
Create Task is both documented and and meets all of the college board requirements. 1/1
Runtime of code on replit is both documented and works on github pages 1/1
Hack #1 is both completed and documented in IntelliJ 1/1
-.5 for Hack 2 and 3 combined for not having logout working 1.5/2
Does not have extra credit
Final Score: 4.5/5
